In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as skl

In [4]:
df = pd.read_csv('Trend_tabell7.csv', index_col=0)
df

Stations Q- trend dir 5%  Q- trend 5% Q- trend dir 30%  Q- trend 30%  \
0       2.13.0        no trend            0       increasing             1   
1       2.32.0      increasing            1       increasing             1   
2      2.142.0        no trend            0       increasing             1   
3      2.268.0        no trend            0       increasing             1   
4      2.279.0      increasing            1       increasing             1   
..         ...             ...          ...              ...           ...   
118    308.1.0        no trend            0         no trend             0   
119    311.4.0        no trend            0         no trend             0   
120  311.460.0      increasing            1       increasing             1   
121   313.10.0        no trend            0         no trend             0   
122    200.4.0      decreasing           -1       decreasing            -1   

    AM30year trend dir  AM30year trend 5% AM7year trend dir  AM7year trend 5%  \
0             no trend                  0          no trend                 0   
1           increasing                  1        increasing                 1   
2             no trend                  0          no trend                 0   
3             no trend                  0          no trend                 0   
4             no trend                  0          no trend                 0   
..                 ...                ...               ...               ...   
118           no trend                  0          no trend                 0   
119           no trend                  0          no trend                 0   
120         increasing                  1        increasing                 1   
121           no trend                  0          no trend                 0   
122           no trend                  0        decreasing                -1   

    AM30summer trend dir  ...  Mean SD max Mean SWE trend    Mean SWE  \
0               no trend  ...  1879.197245           -1.0  271.364320   
1             increasing  ...   794.471094            0.0   85.878275   
2               no trend  ...   768.382971            0.0   53.060611   
3               no trend  ...  1549.467074            0.0  225.350191   
4             increasing  ...  1013.364774            0.0   76.034943   
..                   ...  ...          ...            ...         ...   
118             no trend  ...  1557.724216            0.0  169.142100   
119             no trend  ...          NaN            NaN         NaN   
120           increasing  ...   900.118874            0.0   83.155907   
121             no trend  ...   582.628806            0.0   31.181174   
122             no trend  ...  1769.760226           -1.0  205.946311   

    Mean SM trend     Mean SM Mean E trend    Mean E   Q- spec  Q-95 spec  \
0             1.0   58.001339          1.0  0.392531  0.040479   0.003092   
1             0.0   93.734395          1.0  0.656346  0.022064   0.003801   
2             0.0  137.502855          1.0  1.167794  0.015290   0.002243   
3             1.0   63.378361          1.0  0.365685  0.032949   0.001210   
4             1.0  136.724436          1.0  1.202469  0.020517   0.002812   
..            ...         ...          ...       ...       ...        ...   
118           0.0   98.330120          1.0  0.881928  0.032544   0.003310   
119           NaN         NaN          1.0  0.860267  0.013343   0.004790   
120           0.0  109.441859          1.0  0.868440  0.020793   0.004590   
121           0.0  154.597927          1.0  1.268005  0.014885   0.001515   
122           1.0   99.234303          1.0  0.815653  0.056671   0.011043   

     Q-5 spec  
0    0.140864  
1    0.061089  
2    0.051580  
3    0.123819  
4    0.069168  
..        ...  
118  0.122087  
119  0.032317  
120  0.058239  
121  0.047417  
122  0.155203  

[123 rows x 69 columns]

In [21]:
df = df.dropna()

In [28]:
from sklearn.model_selection import train_test_split
"""
X = df[['Area', 'Lon',
       'Lat', '%_agr', '%_lake', '%_bog', '%_eff_lake',
       '%_forest', '%_glacier', '%_mountain', '%_urban',
       'H min', 'H max', 'L catchment']]
"""
X7 = df[['AM7year trend 5%', 'AM7summer trend 5%', 'AM7winter trend 5%',
       'AM7spring trend 30%', 'AM7autumn trend 30%', 'Area', 'Lon', 'Lat', '%_agr', '%_lake', '%_bog', '%_eff_lake', 
       '%_forest', '%_glacier', '%_mountain', '%_urban', 'H min', 'H max', 'L catchment', 'Q- spec',
       'Q-95 spec', 'Q-5 spec', 'P-', 'P- trend', 'P- min', 'P- max', 
       'T-', 'T- trend', 'T- min', 'T- max', 'SD max trend', 
       'Mean SD max', 'Mean SWE trend', 'Mean SWE', 'Mean SM trend', 'Mean SM', 'Mean E trend', 
       'Mean E']]

target7 = df[['AM7year trend 5%', 'AM7summer trend 5%', 'AM7winter trend 5%',
       'AM7spring trend 30%', 'AM7autumn trend 30%']]


In [34]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
for i in target7:
       y = target7[i]
       X_target7 = X7.drop(i, axis=1)

       X_train7, X_test7, y_train7, y_test7 = train_test_split(X_target7, y, test_size=0.33, random_state=42, stratify=y)
       clf_dc = tree.DecisionTreeClassifier()
       clf_dc = clf_dc.fit(X_train7, y_train7)
       scores = cross_val_score(clf_dc, X_target7, y, cv=5)
       print(cross_val_predict(clf_dc, X_target7, y))
       print(scores)

[ 0  1  0  0  0  1  1  1  0  0  1  0  0  1  0  0  0  1  0  1  0  1  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0 -1  0  0 -1
  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 -1  0  0  0  1  1  0  0 -1  0 -1 -1 -1 -1 -1 -1 -1 -1  0 -1  0 -1 -1 -1
 -1 -1 -1  0  0  0  1  1 -1]
[0.66666667 0.85714286 0.9047619  0.80952381 0.28571429]
[ 0  0  0  0  1  0  0  0 -1  1  0  0  0  0 -1  1  0  1  1  0  1  1  0  1
  0  1  1  1  0  0  1  1  1  0  0  1  0  0  0  1  0  1  1  1  0  0  1  1
  0  0  0  0  0  0  0  0  0  1  0  1  0  0  0 -1  0  1 -1  0  0  0  0 -1
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  1  1 -1]
[0.28571429 0.61904762 0.57142857 0.71428571 0.76190476]
[ 0  0  0  0  0  0  0 -1  0  0  0  0  0  1  1  0  0  0  1 -1  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0
  0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0
  1  0  0  0 -1  0  0  0 

In [19]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train)
X_scaled = scaler.transform(X_train)
X_scaled

array([[-0.17501096, -0.56882581, -0.79670153, ...,  0.68787892,
         0.08883754,  0.68220412],
       [ 0.94380422,  1.81615282,  1.75632122, ..., -1.17509904,
        -1.09704313, -1.10344901],
       [-0.2340808 ,  0.55857427,  0.33182893, ...,  0.66081304,
        -0.16198769,  0.91779712],
       ...,
       [ 0.05717657,  1.63284782,  1.16600863, ..., -0.31330656,
        -0.03201426, -0.29010128],
       [-0.12710065, -0.36840119, -0.92528353, ...,  1.10909818,
         1.39586383,  1.0631657 ],
       [ 0.04794632, -0.61494987, -0.79707899, ...,  0.49827055,
        -0.06001105,  0.53267862]])

In [13]:
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)

In [14]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
scores = cross_val_score(clf, X, y, cv=10)
scores

/Users/mac/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/model_selection/_split.py:666: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


array([0.07692308, 0.53846154, 0.53846154, 0.83333333, 0.83333333,
       0.66666667, 0.75      , 0.75      , 0.58333333, 0.75      ])

In [26]:
from sklearn import tree
clf_dc = tree.DecisionTreeClassifier()
clf_dc = clf_dc.fit(X_train, y_train)
scores = cross_val_score(clf_dc, X, y, cv=10)
scores

/Users/mac/anaconda3/envs/py39/lib/python3.9/site-packages/sklearn/model_selection/_split.py:666: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


array([0.72727273, 0.54545455, 0.90909091, 0.90909091, 0.81818182,
       0.8       , 0.6       , 0.7       , 0.7       , 0.8       ])

LogisticRegression(max_iter=500, solver='newton-cg')